package models;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * Demonstrate the following relationships in the Ebean ORM:
 * <pre>{@code
 * Each dorm room has 0 - N students
 * Each student has 0 - 1 dorm rooms (students may live off campus)
 *
 * +---------------------------------+       +---------------------------------+
 * | DormRoom                        |O|---O<| Student                         |
 * +---------------------------------+       +---------------------------------+
 *
 * @OneToMany(mappedBy = "dormRoom")         @ManyToOne
 * public List<Student> students;            public DormRoom dormRoom;
 * }</pre>
 * In order to support this relationship, a column <em>is</em> added to the
 * database table that represents this Java class, as shown below.
 * <pre>{@code
 * Each parking space has 0 - 1 students
 * Each student has 0 - 1 parking spaces (limit 1 space per student)
 *
 * +---------------------------------+       +---------------------------------+
 * | ParkingSpace                    |O|---|O| Student                         |
 * +---------------------------------+       +---------------------------------+
 *
 * @OneToOne(mappedBy                        @OneToOne
 *         = "parkingSpace")                 public ParkingSpace parkingSpace;
 * public Student student;
 * }</pre>
 * The absence of {@code mappedBy} marks this side of this {@code @OneToOne} as
 * analogous to {@code @ManyToOne}, the "one" side of a {@code @OneToMany} /
 * {@code @ManyToOne} relationship, only with the cardinality of the "many" side
 * limited to one.
 * <p>
 * In order to support this relationship, a column <em>is</em> added to the
 * database table that represents this Java class, with a uniqueness constraint
 * to limit the cardinality to one, as shown below.
 * <p>
 * Here is the MySQL database table generated by the Ebean ORM:
 * <pre>{@code
 * mysql> DESCRIBE student;
 * +------------------+--------------+------+-----+---------+----------------+
 * | Field            | Type         | Null | Key | Default | Extra          |
 * +------------------+--------------+------+-----+---------+----------------+
 * | id               | int(11)      | NO   | PRI | NULL    | auto_increment |
 * | name             | varchar(255) | YES  |     | NULL    |                |
 * | dorm_room_id     | int(11)      | YES  | MUL | NULL    |                |
 * | parking_space_id | int(11)      | YES  | UNI | NULL    |                |
 * +------------------+--------------+------+-----+---------+----------------+
 * 4 rows in set (0.00 sec)
 *
 * }</pre>
 */
@Entity
@SuppressWarnings("WeakerAccess")
public class Student extends CollegeModel {

    @ManyToOne // Default: optional = true
    public DormRoom dormRoom;

    @OneToOne // Default: optional = true
    public ParkingSpace
            parkingSpace;

    public Student(String name, DormRoom dormRoom, ParkingSpace parkingSpace) {
        super(name);
        this.dormRoom = dormRoom;
        this.parkingSpace = parkingSpace;
        this.save();

        if (this.dormRoom != null) {
            this.dormRoom.refresh();
        }

        if (this.parkingSpace != null) {
            this.parkingSpace.refresh();
        }

        System.out.println("Created " + this);
    }

    public String getDescription() {
        StringBuilder sb = new StringBuilder(this.toString());

        sb.append(" has ");

        if (dormRoom == null) {
            sb.append("no ").append(DormRoom.class.getSimpleName())
                    .append(" object");
        } else {
            sb.append(dormRoom);
        }

        sb.append(", ");

        if (parkingSpace == null) {
            sb.append("no ").append(ParkingSpace.class.getSimpleName())
                    .append(" object");
        } else {
            sb.append(parkingSpace);
        }

        return sb.toString();
    }

}
